window.deutsch = {
    "authorName": "Iman Emadi",
    "authorTitle": "Full Stack Entwickler",
    "w_about": "Persönliche Daten",
    "w_skills": "Fähigkeiten",
    "w_experience": "Berufserfahrung",
    "w_education": "Ausbildung",
    "w_contact": "Kontakt",
    "w_theme": "Thema",
    "w_dark": "dunkel ",
    "w_light": "licht",
    "w_language": "Sprache",
    "cvDownload": "CV herunterladen",
    "hireMe": "einstellen",
    "aboutMeContent": "Ich bin ein Full-Stack-Entwickler, <br/> ich habe Erfahrung in Javascript und PHP und habe mit verschiedenen Frameworks und Bibliotheken wie Reactjs, AngularJS, EJS, Mongoose, Redux, Bootstrap und ... gearbeitet. <br/> Ich habe auch Erfahrung mit SQL & MongoDB, SCSS, ReactNative und Cordova. Ich habe auch an ReactNative-Projekten für Android und IOS-Plattformen vor kurzem gearbeitet.",
    "w_bio": "Bio",
    "w_age": "Alter",
    "w_email": "Email",
    "w_discord": "Discord",
    "w_address": "Adresse",
    "address": "Iran , Tehran",
    "w_phone": "Telefon-Nummer",
    "skills": "Fähigkeiten",
    "w_master": "Fachkraft",
    "w_good": "Gut",
    "w_familiar": "vertraut",
    "w_at": "an der",
    "fullStackDev": "Full Stack Entwickler",
    "linksExperience": "eine Website, auf der die Nutzer ihre Geschäfts- und Kontaktinformationen anzeigen können ",
    "bizExperience": "eine Website, an die Nutzer ihren Lebenslauf senden und sich auf eine Stelle bewerben können",
    "universityEdu": "Bachelor in Computertechnik",
    "uniName": "Azad-Universität",
    "uniEduDetail": "Bachelor in Computertechnik, Software (Objektorientierte Programmierung)",
    "schoolEdu": "Hochschulabschluss in Mathematik und Physik",
    "schoolName": "Kamal-Gymnasium",
    "schoolEduDetail": "Mathematik und Physik studiert haben",
    "label_name": "vollständiger Name",
    "label_email": "Email",
    "label_message": "Nachricht",
    "w_send": "Senden",
}
