window.deutsch = {
    "authorName": "Iman Emadi",
    "authorTitle": "Full Stack Developer",
    "w_about": "About me",
    "w_skills": "skills",
    "w_experience": "Experiences",
    "w_education": "Education",
    "w_contact": "Contact",
    "w_theme": "theme",
    "w_dark": "dark",
    "w_light": "light",
    "w_language": "language",
    "cvDownload": "Download CV",
    "hireMe": "HIRE ME",
    "aboutMeContent": "i am a full stack developer , i have experience in Javascript and PHP and have worked with various frameworks and libraries such as Reactjs , AngularJS , EJS , Mongoose , Redux , Bootstrap and ... . i have also experience with SQL & MongoDB , SCSS , ReactNative and Cordova . my main field is web designing and programming , but i have also been working on ReactNative projects for android and IOS platforms , and also PWA with Reactjs ",
    "w_bio": "Bio",
    "w_age": "Age",
    "w_email": "Email",
    "w_discord": "Discord",
    "w_address": "Address",
    "address": "Iran , Tehran",
    "w_phone": "Phone",
    "skills": "Skills",
    "w_master": "Skilled",
    "w_good": "Good",
    "w_familiar": "familiar",
    "w_at": "at",
    "fullStackDev": "FullStack Developer",
    "linksExperience": "designed and programmed a website where different businesses can display their contact information beside a short brief of themselves.",
    "bizExperience": "designed and programmed a website for the company , where employees can submit their resume and apply for a job .",
    "universityEdu": "Bachelor in Computer Engineering",
    "uniName": "Islamic Azad University",
    "uniEduDetail": "Bachelor in Computer engineering , software (Object-oriented programming)",
    "schoolEdu": "graduated in mathematics and Physics",
    "schoolName": "Kamal HighSchool",
    "schoolEduDetail": "studied mathematics and Physics",
    "label_name": "Full name",
    "label_email": "Email",
    "label_message": "Message",
}
